### ISSUE TITLE
Left and right margins are swapped

### ISSUE THREAD

**Issue by P2-718na** [uio-latex/phduio-article-based#10]
Odd pages have a bigger margin on the right side and even pages have more margin on the left side. If the document is set up for
printing, it should be the opposite.

**Comment by martinhelso** [comment]
No, the outer margins should always be bigger than the inner margins when printing. This is because in the printed material, the two inner margins are next to each other, thereby doubling the whitespace. This will look out of balance unless the inner margins are smaller. The part of the inner margin that is lost to the binding is negligible compared to this effect.
